import { siteContentSchema } from './siteContentSchema';

const RAW_SITE_CONTENT = {
    media: {
        heroBackgroundSrc: '/media/hero-warehouse.png',
        heroBackgroundAlt: 'Operacion logistica en almacen con unidad de reparto',
        appleBackgroundSrc: '/media/furgoneta-hero.jpg',
        appleBackgroundAlt: 'Unidad de reparto en operacion logistica nocturna',
        statsBackgroundSrc: '/media/stats-cinematic.svg',
        statsBackgroundAlt: 'Fondo cinematografico de metricas logisticas',
    },
    brand: {
        legalName: 'Postal Express SAC',
        logoPrimary: 'POSTAL',
        logoSecondary: 'Express SAC',
        footerBrand: 'POSTAL EXPRESS',
    },
    nav: {
        servicesLabel: 'Servicios',
        trackingLabel: 'Tracking',
        coverageLabel: 'Cobertura',
    },
    contact: {
        phoneDisplay: '996983530',
        contractsLabel: 'Contratos',
        phoneHref: 'tel:+51996983530',
        whatsappHref: 'https://wa.me/51996983530',
        sectionTitle: 'Informacion del servicio',
        sectionSubtitlePrefix: 'Contratos y coordinaciones:',
    },
    hero: {
        badge: 'Postal Express SAC',
        titleMain: 'Logistica corporativa.',
        titleSub: 'Redefinida.',
        description: '15 anos de experiencia entregando seguridad, control y confianza en Lima, Callao y Provincias.',
        primaryCta: 'Solicitar servicio',
    },
    tracking: {
        title: 'Tracking Postal Express',
        subtitle: 'Seguimiento integral desde el recojo en cliente hasta la entrega al destinatario, con sistema de control y seguridad.',
        inputPlaceholder: 'Ejem: PE-2024-001',
        submitLabel: 'RASTREAR',
        resultGuideLabel: 'Guia',
        resultEstimatedLabel: 'Estimado',
        resetLabel: 'Nueva busqueda',
        timeline: [
            {
                title: 'Recojo - orden de servicio',
                detail: 'Control en instalaciones del cliente',
                state: 'completed',
            },
            {
                title: 'Habilitacion documentaria',
                detail: 'Ensobrado, etiquetado, embolsado y cargo',
                state: 'completed',
            },
            {
                title: 'Distribucion en curso',
                detail: 'Lima, Callao y sedes de Provincia',
                state: 'current',
            },
            {
                title: 'Entrega o devolucion',
                detail: 'Titular/apoderado o devolucion tras 03 visitas',
                state: 'pending',
            },
        ],
    },
    apple: {
        headingHtml: 'Control <br> Integrado.',
        subheading: 'El seguimiento inicia al recojo y culmina al entregar documentos, paqueteria, carnets y diplomas.',
    },
    truck: {
        headlineHtml: 'Del recojo<br>a la entrega.',
        subheading: 'Flujo diario con 03 visitas y reporte de cargos en 24 horas.',
        originLabel: 'Origen',
        destinationLabel: 'Destino',
        scrollCue: 'Sigue scrolleando',
        statuses: [
            'Recojo registrado',
            'Despacho a sede',
            'Distribucion en curso',
            'Entrega o devolucion',
        ],
        waypoints: [
            {
                left: '16%',
                iconClass: 'fa-solid fa-clipboard-check',
                title: 'Recojo',
                subtitle: 'Cliente',
                isHome: false,
            },
            {
                left: '38%',
                iconClass: 'fa-solid fa-envelope-open-text',
                title: 'Habilitacion',
                subtitle: 'Documentos',
                isHome: false,
            },
            {
                left: '60%',
                iconClass: 'fa-solid fa-building',
                title: 'Sede destino',
                subtitle: 'Lima o Provincia',
                isHome: false,
            },
            {
                left: '85%',
                iconClass: 'fa-solid fa-house',
                title: 'Entrega',
                subtitle: 'Domicilio',
                isHome: true,
            },
        ],
    },
    features: {
        titleHtml: 'Mensajeria y logistica<br>local y provincias.',
        items: [
            {
                iconClass: 'fa-solid fa-truck-fast',
                title: 'Recojo y distribucion',
                description: 'Recojo y distribucion en minivan, autos y motorizados para Lima, Callao y Provincias.',
            },
            {
                iconClass: 'fa-solid fa-shield-halved',
                title: 'Seguridad documental',
                description: 'Diplomas y documentos valorados en estantes metalicos bajo llave y control de custodia.',
            },
            {
                iconClass: 'fa-solid fa-bell',
                title: 'Flujo operativo',
                description: 'Despacho por pedidos, distribucion diaria a domicilios y personal capacitado y uniformado.',
            },
            {
                iconClass: 'fa-solid fa-file-lines',
                title: 'Reportes y cargos',
                description: 'Reporte cada 48 horas, reporte final y entrega de cargos 24 horas despues del cierre.',
            },
        ],
        mockup: {
            coverageChip: 'Lima - Callao - Provincias',
            pickupTextHtml: 'Recojo programado<br>y ruta asignada',
            pickupTagOne: 'Minivan y autos',
            pickupTagTwo: 'Motorizados',
            shieldText: 'Custodia documentaria',
            shieldCoverage: 'Estantes metalicos bajo llave',
            notificationOne: 'Recojo confirmado',
            notificationTwo: 'Distribucion en curso',
            notificationThree: 'Entrega o devolucion',
            methodOne: 'Recojo',
            methodTwo: 'Habilitacion',
            methodThree: 'Distribucion',
            methodFour: 'Entrega',
            receiptOneLabel: 'Reporte parcial',
            receiptOneValue: 'Cada 48 h',
            receiptTwoLabel: 'Entrega de cargos',
            receiptTwoValue: '24 h',
            receiptThreeLabel: 'Visitas incluidas',
            receiptThreeValue: '03',
        },
    },
    carousel: {
        slideOne: {
            label: 'Operacion documentaria',
            titleHtml: 'Recojo y<br>habilitacion documental.',
            body: 'Recojo en cliente y preparacion completa con ensobrado, etiquetado, embolsado y cargo estandar.',
            badgeOne: 'Documentos',
            badgeTwo: 'Diplomas',
            badgeThree: 'Carnets',
            phoneTitle: 'Orden de servicio',
            phoneLabel: 'Recojo en cliente',
            phoneCta: 'Iniciar habilitacion ->',
        },
        slideTwo: {
            label: 'Tracking y seguridad',
            titleHtml: 'Seguimiento de<br>principio a fin.',
            body: 'Trazabilidad por etapa para entrega a titular/apoderado y control de incidencias con reposicion en caso fortuito.',
            statOneLabel: 'Reporte parcial',
            statTwoLabel: 'Entrega de cargos',
            phoneTitle: 'En camino',
            routeOne: 'Recojo',
            routeTwo: 'En ruta',
            routeThree: 'Entrega',
            etaPrefix: 'Reporte parcial:',
            etaValue: 'Cada 48 h',
        },
        slideThree: {
            label: 'Cobertura y cumplimiento',
            titleHtml: 'Distribucion local<br>y provincias.',
            body: 'Tiempo local de 1 a 4 dias, flujo a sedes segun pedidos y distribucion diaria hasta culminar servicio.',
            timerOne: '1 a 4 dias',
            timerTwo: 'Servicio diario',
            phoneTitle: 'Entrega final',
            deliveredMessage: 'Titular o apoderado autorizado',
            deliveredTime: 'Cargo entregado en 24 h',
        },
    },
    services: {
        eyebrow: 'Nuestros Servicios',
        title: 'Tramite documentario, valorados, paqueteria y carga',
        cards: [
            {
                badge: 'Documentario',
                badgeClass: 'bg-brand-600',
                title: 'Tramite documentario',
                description: 'Gestion y distribucion de documentos en entidades publicas y privadas con control de cargo.',
                cta: 'Servicio especializado',
                imageSrc: '/media/service-docs-cinematic.svg',
                imageAlt: 'Fondo cinematico de tramite documentario',
            },
            {
                badge: 'Valorados',
                badgeClass: 'bg-slate-800',
                title: 'Documentos valorados y diplomas',
                description: 'Custodia segura, entrega a titular o apoderado y devolucion despues de 03 visitas infructuosas.',
                cta: 'Custodia y trazabilidad',
                imageSrc: '/media/service-valued-cinematic.svg',
                imageAlt: 'Fondo cinematico de documentos valorados',
            },
            {
                badge: 'Paqueteria',
                badgeClass: 'bg-accent-500',
                title: 'Paqueteria y carga',
                description: 'Embalaje de cajas y paqueteria con despacho continuo a sedes de Provincia y entrega domiciliaria.',
                cta: 'Cobertura nacional',
                imageSrc: '/media/service-parcel-cinematic.svg',
                imageAlt: 'Fondo cinematico de paqueteria y carga',
            },
        ],
    },
    serviceCharacteristics: {
        title: 'Caracteristicas del servicio',
        items: [
            'Recojo y distribucion en minivan, autos y motorizados.',
            'Tiempo de distribucion local de 1 a 4 dias.',
            'Diplomas y valorados en estantes metalicos bajo llave.',
            'Ensobrado, embolsado, etiquetado y cargo de documentos.',
            'Embalaje de cajas y paqueteria.',
            'Personal capacitado, uniformado y con conocimiento de rutas.',
            'Flujo de envios a sedes segun pedidos.',
            'Distribucion diaria a domicilios hasta culminar el servicio.',
            'Servicio con 03 visitas incluidas.',
            'Reposicion asumida por Postal Express en caso fortuito de deterioro o robo.',
            'Entrega de cargos en 24 horas despues de culminar el servicio.',
            'Reporte de distribucion cada 48 horas y reporte final de cierre.',
        ],
    },
    flow: {
        title: 'Flujo de servicio Postal Express',
        steps: [
            {
                iconClass: 'fa-solid fa-clipboard-check',
                iconWrapperClass: 'w-24 h-24 bg-white border-4 border-brand-50 rounded-full flex items-center justify-center text-brand-600 text-3xl mx-auto mb-6 shadow-xl',
                title: '1. Recojo y control',
                description: 'Registro con orden de servicio y control de ingreso desde las instalaciones del cliente.',
            },
            {
                iconClass: 'fa-solid fa-box-open',
                iconWrapperClass: 'w-24 h-24 bg-brand-600 border-4 border-brand-200 rounded-full flex items-center justify-center text-white text-3xl mx-auto mb-6 shadow-xl ring-4 ring-brand-50',
                title: '2. Habilitacion y despacho',
                description: 'Preparacion documentaria y embalaje para despacho local o a sedes de Provincia.',
            },
            {
                iconClass: 'fa-solid fa-circle-check',
                iconWrapperClass: 'w-24 h-24 bg-white border-4 border-green-50 rounded-full flex items-center justify-center text-green-500 text-3xl mx-auto mb-6 shadow-xl',
                title: '3. Entrega y cierre',
                description: 'Entrega al destinatario, reporte final y cargos 24 horas despues de culminar.',
            },
        ],
    },
    stats: {
        items: [
            { target: 15, suffix: '+', label: 'Anos de experiencia' },
            { target: 3, suffix: '+', label: 'Visitas por envio' },
            { target: 48, suffix: 'h', label: 'Reporte parcial' },
            { target: 24, suffix: 'h', label: 'Entrega de cargos' },
        ],
    },
    faq: {
        items: [
            {
                question: 'Que incluye el servicio de Postal Express?',
                answer: 'Tramite documentario, distribucion de valorados, paqueteria, obsequios y servicios logisticos en Lima, Callao y Provincias.',
            },
            {
                question: 'Como protegen documentos y diplomas?',
                answer: 'Se almacenan bajo llave y se habilitan con ensobrado, etiquetado, embolsado y cargo para control completo.',
            },
            {
                question: 'Cuales son tiempos y visitas de distribucion?',
                answer: 'Tiempo local de 1 a 4 dias. El servicio contempla hasta 03 visitas antes de la devolucion en sede.',
            },
            {
                question: 'Cuando entregan reportes y cargos?',
                answer: 'Reporte de distribucion cada 48 horas, reporte final al cierre y cargos dentro de 24 horas.',
            },
            {
                question: 'Que pasa ante deterioro o robo?',
                answer: 'Postal Express asume la reposicion del documento en caso fortuito de deterioro o robo.',
            },
        ],
    },
    ticker: {
        items: [
            { iconClass: 'fa-solid fa-file-signature text-3xl', label: 'Tramite documentario' },
            { iconClass: 'fa-solid fa-envelope-open-text text-3xl', label: 'Documentos valorados' },
            { iconClass: 'fa-solid fa-box text-3xl', label: 'Paqueteria y carga' },
            { iconClass: 'fa-solid fa-gift text-3xl', label: 'Servicios logisticos generales' },
            { iconClass: 'fa-solid fa-map-location-dot text-3xl', label: 'Lima, Callao y Provincias' },
        ],
    },
    footer: {
        intro: 'Postal Express SAC cuenta con 15 anos de experiencia en mensajeria y servicios postales para clientes institucionales y corporativos.',
        whatsappLabel: 'WhatsApp 996983530',
        companyHeading: 'Empresa',
        coverageHeading: 'Cobertura',
        contractsHeading: 'Contratos',
        contractsDescription: 'Atencion comercial y coordinaciones de servicio.',
        signoff: ['Atentamente', 'Jose Mejia Tejada', 'Gerente General'],
        copyright: '&copy; 2026 Postal Express SAC.',
        companyItems: [
            'Postal Express SAC',
            'Gerencia General',
            'Jose Mejia Tejada',
        ],
        coverageItems: [
            'Lima y Callao',
            'Sedes en Provincias',
            'Distribucion diaria',
        ],
    },
} as const;

export const SITE_CONTENT = siteContentSchema.parse(RAW_SITE_CONTENT);

export type { SiteContent } from './siteContentSchema';
