import { siteContentSchema } from './siteContentSchema';

const RAW_SITE_CONTENT = {
    media: {
        heroBackgroundSrc: '/media/hero-warehouse.png',
        heroBackgroundAlt: 'Operación logística en almacén con unidad de reparto',
        appleBackgroundSrc: '/media/furgoneta-hero.jpg',
        appleBackgroundAlt: 'Unidad de reparto en operación logística nocturna',
        statsBackgroundSrc: '/media/stats-cinematic.svg',
        statsBackgroundAlt: 'Fondo cinematográfico de métricas logísticas',
    },
    brand: {
        legalName: 'Postal Express SAC',
        logoPrimary: 'POSTAL',
        logoSecondary: 'Express SAC',
        footerBrand: 'POSTAL EXPRESS',
    },
    nav: {
        servicesLabel: 'Servicios',
        trackingLabel: 'Tracking',
        coverageLabel: 'Cobertura',
    },
    contact: {
        phoneDisplay: '996983530',
        contractsLabel: 'Contratos',
        phoneHref: 'tel:+51996983530',
        whatsappHref: 'https://wa.me/51996983530',
        sectionTitle: 'Información del servicio',
        sectionSubtitlePrefix: 'Contratos y coordinaciones:',
    },
    hero: {
        badge: 'Postal Express SAC',
        titleMain: 'Logística corporativa.',
        titleSub: 'Redefinida.',
        description: '15 años de experiencia entregando seguridad, control y confianza en Lima, Callao y Provincias.',
        primaryCta: 'Solicitar servicio',
    },
    tracking: {
        title: 'Tracking Postal Express',
        subtitle: 'Seguimiento integral desde el recojo en cliente hasta la entrega al destinatario, con sistema de control y seguridad.',
        inputPlaceholder: 'Ejem: PE-2024-001',
        submitLabel: 'RASTREAR',
        resultGuideLabel: 'Guía',
        resultEstimatedLabel: 'Estimado',
        resetLabel: 'Nueva búsqueda',
        timeline: [
            {
                title: 'Recojo - orden de servicio',
                detail: 'Control en instalaciones del cliente',
                state: 'completed',
            },
            {
                title: 'Habilitación documentaria',
                detail: 'Ensobrado, etiquetado, embolsado y cargo',
                state: 'completed',
            },
            {
                title: 'Distribución en curso',
                detail: 'Lima, Callao y sedes de Provincia',
                state: 'current',
            },
            {
                title: 'Entrega o devolución',
                detail: 'Titular/apoderado o devolución tras 03 visitas',
                state: 'pending',
            },
        ],
    },
    apple: {
        headingHtml: 'Control <br> Integrado.',
        subheading: 'El seguimiento inicia al recojo y culmina al entregar documentos, paquetería, carnés y diplomas.',
    },
    truck: {
        headlineHtml: 'Del recojo<br>a la entrega.',
        subheading: 'Flujo diario con 03 visitas y reporte de cargos en 24 horas.',
        originLabel: 'Origen',
        destinationLabel: 'Destino',
        scrollCue: 'Sigue scrolleando',
        statuses: [
            'Recojo registrado',
            'Despacho a sede',
            'Distribución en curso',
            'Entrega o devolución',
        ],
        waypoints: [
            {
                left: '16%',
                iconClass: 'fa-solid fa-clipboard-check',
                title: 'Recojo',
                subtitle: 'Cliente',
                isHome: false,
            },
            {
                left: '38%',
                iconClass: 'fa-solid fa-envelope-open-text',
                title: 'Habilitación',
                subtitle: 'Documentos',
                isHome: false,
            },
            {
                left: '60%',
                iconClass: 'fa-solid fa-building',
                title: 'Sede destino',
                subtitle: 'Lima o Provincia',
                isHome: false,
            },
            {
                left: '85%',
                iconClass: 'fa-solid fa-house',
                title: 'Entrega',
                subtitle: 'Domicilio',
                isHome: true,
            },
        ],
    },
    features: {
        titleHtml: 'Mensajería y logística<br>local y provincias.',
        items: [
            {
                iconClass: 'fa-solid fa-truck-fast',
                title: 'Recojo y distribución',
                description: 'Recojo y distribución en minivan, autos y motorizados para Lima, Callao y Provincias.',
            },
            {
                iconClass: 'fa-solid fa-shield-halved',
                title: 'Seguridad documental',
                description: 'Diplomas y documentos valorados en estantes metálicos bajo llave y control de custodia.',
            },
            {
                iconClass: 'fa-solid fa-bell',
                title: 'Flujo operativo',
                description: 'Despacho por pedidos, distribución diaria a domicilios y personal capacitado y uniformado.',
            },
            {
                iconClass: 'fa-solid fa-file-lines',
                title: 'Reportes y cargos',
                description: 'Reporte cada 48 horas, reporte final y entrega de cargos 24 horas después del cierre.',
            },
        ],
        mockup: {
            coverageChip: 'Lima - Callao - Provincias',
            pickupTextHtml: 'Recojo programado<br>y ruta asignada',
            pickupTagOne: 'Minivan y autos',
            pickupTagTwo: 'Motorizados',
            shieldText: 'Custodia documentaria',
            shieldCoverage: 'Estantes metálicos bajo llave',
            notificationOne: 'Recojo confirmado',
            notificationTwo: 'Distribución en curso',
            notificationThree: 'Entrega o devolución',
            methodOne: 'Recojo',
            methodTwo: 'Habilitación',
            methodThree: 'Distribución',
            methodFour: 'Entrega',
            receiptOneLabel: 'Reporte parcial',
            receiptOneValue: 'Cada 48 h',
            receiptTwoLabel: 'Entrega de cargos',
            receiptTwoValue: '24 h',
            receiptThreeLabel: 'Visitas incluidas',
            receiptThreeValue: '03',
        },
    },
    carousel: {
        slideOne: {
            label: 'Operación documentaria',
            titleHtml: 'Recojo y<br>habilitación documental.',
            body: 'Recojo en cliente y preparación completa con ensobrado, etiquetado, embolsado y cargo estándar.',
            badgeOne: 'Documentos',
            badgeTwo: 'Diplomas',
            badgeThree: 'Carnés',
            phoneTitle: 'Orden de servicio',
            phoneLabel: 'Recojo en cliente',
            phoneCta: 'Iniciar habilitación ->',
        },
        slideTwo: {
            label: 'Tracking y seguridad',
            titleHtml: 'Seguimiento de<br>principio a fin.',
            body: 'Trazabilidad por etapa para entrega a titular/apoderado y control de incidencias con reposición en caso fortuito.',
            statOneLabel: 'Reporte parcial',
            statTwoLabel: 'Entrega de cargos',
            phoneTitle: 'En camino',
            routeOne: 'Recojo',
            routeTwo: 'En ruta',
            routeThree: 'Entrega',
            etaPrefix: 'Reporte parcial:',
            etaValue: 'Cada 48 h',
        },
        slideThree: {
            label: 'Cobertura y cumplimiento',
            titleHtml: 'Distribución local<br>y provincias.',
            body: 'Tiempo local de 1 a 4 días, flujo a sedes según pedidos y distribución diaria hasta culminar servicio.',
            timerOne: '1 a 4 días',
            timerTwo: 'Servicio diario',
            phoneTitle: 'Entrega final',
            deliveredMessage: 'Titular o apoderado autorizado',
            deliveredTime: 'Cargo entregado en 24 h',
        },
    },
    services: {
        eyebrow: 'Nuestros Servicios',
        title: 'Trámite documentario, valorados, paquetería y carga',
        cards: [
            {
                badge: 'Documentario',
                badgeClass: 'bg-brand-600',
                title: 'Trámite documentario',
                description: 'Gestión y distribución de documentos en entidades públicas y privadas con control de cargo.',
                cta: 'Servicio especializado',
                imageSrc: '/media/docs_cinematic.png',
                imageAlt: 'Personal operando trámite documentario',
            },
            {
                badge: 'Valorados',
                badgeClass: 'bg-slate-800',
                title: 'Documentos valorados y diplomas',
                description: 'Custodia segura, entrega a titular o apoderado y devolución después de 03 visitas infructuosas.',
                cta: 'Custodia y trazabilidad',
                imageSrc: '/media/valued_cinematic.png',
                imageAlt: 'Custodia segura de documentos valorados',
            },
            {
                badge: 'Paquetería',
                badgeClass: 'bg-accent-500',
                title: 'Paquetería y carga',
                description: 'Embalaje de cajas y paquetería con despacho continuo a sedes de Provincia y entrega domiciliaria.',
                cta: 'Cobertura nacional',
                imageSrc: '/media/parcel_cinematic.png',
                imageAlt: 'Operación de paquetería y carga',
            },
        ],
    },
    serviceCharacteristics: {
        title: 'Características del servicio',
        items: [
            'Recojo y distribución en minivan, autos y motorizados.',
            'Tiempo de distribución local de 1 a 4 días.',
            'Diplomas y valorados en estantes metálicos bajo llave.',
            'Ensobrado, embolsado, etiquetado y cargo de documentos.',
            'Embalaje de cajas y paquetería.',
            'Personal capacitado, uniformado y con conocimiento de rutas.',
            'Flujo de envíos a sedes según pedidos.',
            'Distribución diaria a domicilios hasta culminar el servicio.',
            'Servicio con 03 visitas incluidas.',
            'Reposición asumida por Postal Express en caso fortuito de deterioro o robo.',
            'Entrega de cargos en 24 horas después de culminar el servicio.',
            'Reporte de distribución cada 48 horas y reporte final de cierre.',
        ],
    },
    flow: {
        title: 'Flujo de servicio Postal Express',
        steps: [
            {
                iconClass: 'fa-solid fa-clipboard-check',
                iconWrapperClass: 'w-24 h-24 bg-white border-4 border-brand-50 rounded-full flex items-center justify-center text-brand-600 text-3xl mx-auto mb-6 shadow-xl',
                imageSrc: '/media/docs_cinematic.png',
                imageAlt: 'Control documentario y validación de recojo',
                title: '1. Recojo y control',
                description: 'Registro con orden de servicio y control de ingreso desde las instalaciones del cliente.',
            },
            {
                iconClass: 'fa-solid fa-box-open',
                iconWrapperClass: 'w-24 h-24 bg-brand-600 border-4 border-brand-200 rounded-full flex items-center justify-center text-white text-3xl mx-auto mb-6 shadow-xl ring-4 ring-brand-50',
                imageSrc: '/media/furgoneta-hero.jpg',
                imageAlt: 'Habilitación y despacho con unidad de transporte Postal Express',
                title: '2. Habilitación y despacho',
                description: 'Preparación documentaria y embalaje para despacho local o a sedes de Provincia.',
            },
            {
                iconClass: 'fa-solid fa-circle-check',
                iconWrapperClass: 'w-24 h-24 bg-white border-4 border-green-50 rounded-full flex items-center justify-center text-green-500 text-3xl mx-auto mb-6 shadow-xl',
                imageSrc: '/media/parcel_cinematic.png',
                imageAlt: 'Entrega de paquetería y cierre de servicio con confirmación',
                title: '3. Entrega y cierre',
                description: 'Entrega al destinatario, reporte final y cargos 24 horas después de culminar.',
            },
        ],
    },
    stats: {
        items: [
            { target: 15, suffix: '+', label: 'Años de experiencia' },
            { target: 3, suffix: '+', label: 'Visitas por envío' },
            { target: 48, suffix: 'h', label: 'Reporte parcial' },
            { target: 24, suffix: 'h', label: 'Entrega de cargos' },
        ],
    },
    faq: {
        items: [
            {
                question: '¿Qué incluye el servicio de Postal Express?',
                answer: 'Trámite documentario, distribución de valorados, paquetería, obsequios y servicios logísticos en Lima, Callao y Provincias.',
            },
            {
                question: '¿Cómo protegen documentos y diplomas?',
                answer: 'Se almacenan bajo llave y se habilitan con ensobrado, etiquetado, embolsado y cargo para control completo.',
            },
            {
                question: '¿Cuáles son tiempos y visitas de distribución?',
                answer: 'Tiempo local de 1 a 4 días. El servicio contempla hasta 03 visitas antes de la devolución en sede.',
            },
            {
                question: '¿Cuándo entregan reportes y cargos?',
                answer: 'Reporte de distribución cada 48 horas, reporte final al cierre y cargos dentro de 24 horas.',
            },
            {
                question: '¿Qué pasa ante deterioro o robo?',
                answer: 'Postal Express asume la reposición del documento en caso fortuito de deterioro o robo.',
            },
        ],
    },
    ticker: {
        items: [
            { iconClass: 'fa-solid fa-file-signature text-3xl', label: 'Trámite documentario' },
            { iconClass: 'fa-solid fa-envelope-open-text text-3xl', label: 'Documentos valorados' },
            { iconClass: 'fa-solid fa-box text-3xl', label: 'Paquetería y carga' },
            { iconClass: 'fa-solid fa-gift text-3xl', label: 'Servicios logísticos generales' },
            { iconClass: 'fa-solid fa-map-location-dot text-3xl', label: 'Lima, Callao y Provincias' },
        ],
    },
    footer: {
        intro: 'Postal Express SAC cuenta con 15 años de experiencia en mensajería y servicios postales para clientes institucionales y corporativos.',
        whatsappLabel: 'WhatsApp 996983530',
        companyHeading: 'Empresa',
        coverageHeading: 'Cobertura',
        contractsHeading: 'Contratos',
        contractsDescription: 'Atención comercial y coordinaciones de servicio.',
        signoff: ['Atentamente', 'José Mejía Tejada', 'Gerente General'],
        copyright: '&copy; 2026 Postal Express SAC.',
        companyItems: [
            'Postal Express SAC',
            'Gerencia General',
            'José Mejía Tejada',
        ],
        coverageItems: [
            'Lima y Callao',
            'Sedes en Provincias',
            'Distribución diaria',
        ],
    },
} as const;

export const SITE_CONTENT = siteContentSchema.parse(RAW_SITE_CONTENT);

export type { SiteContent } from './siteContentSchema';
